# Generated by Django 4.0.7 on 2022-09-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='NAME')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('image', photo.fields.ThumbnailImageField(blank=True, null=True, upload_to='market/%Y/%m')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='PRICE')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
