# Generated by Django 4.0.7 on 2022-09-27 17:28

from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='owner',
        ),
        migrations.AddField(
            model_name='market',
            name='cate',
            field=models.CharField(blank=re.RegexFlag['TEMPLATE'], max_length=100, verbose_name='CATEGORY'),
        ),
        migrations.AddField(
            model_name='market',
            name='item',
            field=models.CharField(blank=True, max_length=100, verbose_name='ITEM'),
        ),
    ]
