# Generated by Django 4.0.7 on 2022-09-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_market_owner_market_cate_market_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='cate',
        ),
    ]
