# Generated by Django 4.0.7 on 2022-09-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_market_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='NAME')),
            ],
        ),
        migrations.RenameField(
            model_name='market',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='market',
            name='item',
        ),
        migrations.AddField(
            model_name='market',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.cate'),
        ),
    ]
