# Generated by Django 4.0.7 on 2022-09-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_cate_rename_name_market_item_name_remove_market_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'market', 'verbose_name_plural': 'markets'},
        ),
    ]
