# Generated by Django 4.0.7 on 2022-09-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Owner',
            new_name='owner',
        ),
    ]
