# Generated by Django 4.0.7 on 2022-09-23 15:16

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_owner_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=photo.fields.ThumbnailImageField(blank=True, null=True, upload_to='photo/%Y/%m'),
        ),
    ]
