# Generated by Django 4.0.7 on 2022-09-23 16:41

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=photo.fields.ThumbnailImageField(blank=True, null=True, upload_to='post/%Y/%m'),
        ),
    ]
